#!/bin/bash
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/fpctzappfingerprint/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/fpctzappfingerprint/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/goodixfp/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/goodixfp/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/ifaata/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/ifaata/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/mtee/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/common_applib/build/mtee/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/A53_64/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/fpctzappfingerprint/A53_64/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/scorpion/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/fpctzappfingerprint/scorpion/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/A53_64/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/goodixfp/A53_64/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/scorpion/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/goodixfp/scorpion/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/A53_64/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/ifaata/A53_64/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/scorpion/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/ifaata/scorpion/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/A53_64/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/mtee/A53_64/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/proxy/build/sampleapp/scorpion/IADAANAA/tzlib_proxy.lib core/securemsm/trustzone/qsapps/libs/applib/proxy/build/mtee/scorpion/IADAANAA/tzlib_proxy.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee/build/fpctzappfingerprint/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee/build/goodixfp/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee/build/ifaata/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee/build/sampleapp/scorpion/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee/build/mtee/scorpion/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/fpctzappfingerprint/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/goodixfp/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/ifaata/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/sampleapp/A53_64/IADAANAA/tzapp_entrylib.lib core/securemsm/trustzone/qsapps/libs/applib/qsee64/build/mtee/A53_64/IADAANAA/tzapp_entrylib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/A53_64/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/fpctzappfingerprint/A53_64/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/scorpion/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/fpctzappfingerprint/scorpion/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/A53_64/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/goodixfp/A53_64/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/scorpion/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/goodixfp/scorpion/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/A53_64/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/ifaata/A53_64/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/scorpion/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/ifaata/scorpion/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/A53_64/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/mtee/A53_64/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsapps/libs/biometric/build/sampleapp/scorpion/IADAANAA/biometric_lib.lib core/securemsm/trustzone/qsapps/libs/biometric/build/mtee/scorpion/IADAANAA/biometric_lib.lib
cp core/securemsm/trustzone/qsee/mink/libstd/build/sampleapp/scorpion/IADAANAA/libstd.lib core/securemsm/trustzone/qsee/mink/libstd/build/fpctzappfingerprint/scorpion/IADAANAA/libstd.lib
cp core/securemsm/trustzone/qsee/mink/libstd/build/sampleapp/scorpion/IADAANAA/libstd.lib core/securemsm/trustzone/qsee/mink/libstd/build/goodixfp/scorpion/IADAANAA/libstd.lib
cp core/securemsm/trustzone/qsee/mink/libstd/build/sampleapp/scorpion/IADAANAA/libstd.lib core/securemsm/trustzone/qsee/mink/libstd/build/ifaata/scorpion/IADAANAA/libstd.lib
cp core/securemsm/trustzone/qsee/mink/libstd/build/sampleapp/scorpion/IADAANAA/libstd.lib core/securemsm/trustzone/qsee/mink/libstd/build/mtee/scorpion/IADAANAA/libstd.lib
